Add GetAssetType()
Mutagen-Modding/Mutagen pull request #452
Opened 2023-07-17 20:38 UTC by Elscrux

Add GetAssetType() based on file extension and base folder. Tests are included.

@Noggog I had to include a limited version of ConvertToDataRelativePath(), without the base folder check as that already needs information about the asset type. I don't know how to properly do this without copy paste as I'm not very familiar with Spans. If you see a way to do that, feel free to change it :)

2023-07-17 21:43 UTC, Noggog requested changes
Unit tests are failing.  Not immediately apparent why.   Just says that the GetAssetType expected non-null, but got null.. which isn't too helpful.

Maybe as a way to help dig into it, we can define some new unit tests that just flex, say:
- `ConvertToDataRelativePath`.  Maybe the issue is in there, and a more dedicated unit test will expose that
- Make the Types dictionary internal, and write a unit test that queries the dictionary directly to see if what we expect is in there

Hopefully one of those tests will shed light on why the current one is failing on the CI server

2023-07-17 21:43 UTC, Noggog commented on Mutagen.Bethesda.UnitTests/Skyrim/Assets/AssetTypeTests.cs
> +        IAssetType.GetAssetType(GameCategory.Skyrim, "Music\\Special\\Dungeon\\DungeonBoss01.xwm").Should().BeOfType<SkyrimMusicAssetType>();
Linux bois are going to want `Path.Combine` usage here

2023-07-17 21:43 UTC, Noggog commented on Mutagen.Bethesda.Core/Assets/IAssetType.cs
> +    static IAssetType()
Let's move this to another internal class's static constructor.  `GetAssetTypeLocator` or something else.

Putting it here in `IAssetType` means that this reflection code will be less lazy than it could be.  Some code might not be interested in calling `GetAssetType`, but still have to pay this startup price.   If we move it elsewhere, then it's only when `GetAssetType` gets called and accesses `GetAssetTypeLocator` that the reflection will be run

2023-07-17 21:43 UTC, Noggog commented on Mutagen.Bethesda.Core/Assets/IAssetType.cs
> +    public static IAssetType? GetAssetType(GameCategory gameCategory, string path)
Let's rename this to TryGetAssetType.   The fact that it returns nullable means it's a TryGet, as far as Mutagen's patterns elsewhere are concerned.    A function named `GetAssetType` would be one that didn't return null, and threw an exception if it couldn't be converted.   Up to you if you want to define the variants

2023-07-18 18:03 UTC, Elscrux commented
I included the feedback about the code. Maybe the tests also work now because I use Path.Combine instead? I'll wait for the pipeline to run through and try debugging the tests further when they fail.

2023-07-18 18:51 UTC, Elscrux commented
@Noggog Tests should be fixed now. I limited everything to dotnet 7, as the reflection code used to build the dictionary specifically uses dotnet 7 code. There could also be support for dotnet 6 with some tweaks but I left it as it is for now.

If you have any more suggestions, or ideas how to reduce code duplication with the two ConvertToDataRelativePath() functions, let me know. Otherwise I think this is ready to be merged.

2023-07-18 21:09 UTC, Noggog approved these changes

2023-07-18 21:09 UTC, merged