Add IKeyworded.HasKeywords extension methods for IEnumerables
Mutagen-Modding/Mutagen pull request #466
Opened 2023-08-20 20:51 UTC by MarkKoz

Close #415

We could make the non-list methods proxy to the list methods to reduce code duplication (by wrapping the single argument in a list), but wasn't sure it was worthwhile.

2023-08-21 06:32 UTC, Noggog requested changes

2023-08-21 06:32 UTC, Noggog commented on Mutagen.Bethesda.Core/Plugins/Aspects/IKeyworded.cs
> +        public static bool HasKeyword<TKeyword>(
Looking at this closer, I think renaming this to `HasAnyKeyword` will be a better name to describe its behavior.   Leaves open an alternative `HasAllKeywords` or somesuch if we want to add that later

2023-08-21 06:32 UTC, Noggog commented on Mutagen.Bethesda.Core/Plugins/Aspects/IKeyworded.cs
> +        public static bool TryResolveKeyword<TKeyword>(
Maybe if we renamed this to `TryResolveAnyKeyword`, then that'd make more sense with its behavior?  Still a weird function to expose.   `HasAnyKeyword` is being added as it's so very often used, some people have requested it instead of writing the (still simple) Linq statement.

But `TryResolveAnyKeyword` is sort of escaping that reasoning, as it's not something I think people will be too interested in heavily using, and is sort of flooding the intellisense at that point.

At the bare minimum, it's used for the final HasAnyKeyword for editorIDs, so maybe it's useful as a private helper method?

2023-08-21 06:32 UTC, Noggog commented on Mutagen.Bethesda.UnitTests/Plugins/Aspects/IKeywordedTests.cs
> +    public void HasKeyword_ByRecordList_Found()
Tests look good!  If you want to get fancy, feel free to try upgrading them to use the AutoFixture systems.  Let's you do stuff like this:
```
[Theory, MutagenModAutoData]
public void HasKeyword_ByRecordList_NotFound(Npc npc, Keyword keyword2, Keyword keyword3, Keyword keyword4)
{
    npc.Keywords = new ExtendedList<IFormLinkGetter<IKeywordGetter>>();
    npc.Keywords.Add(keyword3.ToLink());
    npc.HasKeyword(ImmutableList.Create(keyword2, keyword4)).Should().BeFalse();
}
```
Where the test systems make the objects for you and handle the uninteresting details that are unrelated to this test.  

The tech does lots of crazy stuff.  Haven't gotten around to documenting it all on the Mutagen wiki, yet

2023-08-26 20:51 UTC, MarkKoz commented on Mutagen.Bethesda.Core/Plugins/Aspects/IKeyworded.cs
> +        public static bool TryResolveKeyword<TKeyword>(
I've renamed the methods and removed the `Try*` methods.

2023-08-26 20:52 UTC, MarkKoz commented on Mutagen.Bethesda.UnitTests/Plugins/Aspects/IKeywordedTests.cs
> +    public void HasKeyword_ByRecordList_Found()
Nice! I've updated the tests to use that. Wasn't sure how to make the most out of it for the editor ID tests.

2023-08-26 20:54 UTC, MarkKoz commented on Mutagen.Bethesda.Core/Plugins/Aspects/IKeyworded.cs
> +                if (cache.TryResolve(keywordForm, out keyword!))
Using the null forgiving operator to avoid a CS8600 error. Not sure if there is a better way to go about this. I cannot use `out TKeyword? keyword` since `TryResolve` does not accept a nullable version of the type.

2023-08-26 21:05 UTC, Noggog commented on Mutagen.Bethesda.Core/Plugins/Aspects/IKeyworded.cs
> +                if (cache.TryResolve(keywordForm, out keyword!))
`if (cache.TryResolve(keywordForm, out var keyword))`
is the way I'd typically write it, as yeah, defining the variable in the line before makes things confused as it's sort of a quantum-null variable.   Perhaps changing L290 to be nullable might work?   But yeah, using `var` is probably the preferred route.

2023-08-26 21:12 UTC, Noggog commented on Mutagen.Bethesda.UnitTests/Plugins/Aspects/IKeywordedTests.cs
> +    public void TryResolveKeyword_ByEditorID_Found(SkyrimMod mod)
There's no way you would know this, as it's tooling I wrote to behave how I want, but I've set up the Mutagen autofixture systems to auto add records when written like this:
`TryResolveKeyword_ByEditorID_Found(SkyrimMod mod, Npc npc, Keyword keyword)`
Both npc and keyword will be added to the mod, so all that wiring below isn't needed

2023-08-26 21:17 UTC, MarkKoz commented on Mutagen.Bethesda.Core/Plugins/Aspects/IKeyworded.cs
> +                if (cache.TryResolve(keywordForm, out keyword!))
When using `var` it chooses a suboptimal overload apparently:
```
CS0618: Method 'Mutagen.Bethesda.Plugins.Cache.ILinkCache.TryResolve(FormKey, out IMajorRecordGetter, ResolveTarget)' is obsolete: This call is not as optimized as its generic typed counterpart. Use as a last resort.```

2023-08-26 21:18 UTC, MarkKoz commented on Mutagen.Bethesda.UnitTests/Plugins/Aspects/IKeywordedTests.cs
> +    public void TryResolveKeyword_ByEditorID_Found(SkyrimMod mod)
Thanks - will keep that in mind!

2023-08-26 21:18 UTC, Noggog commented on Mutagen.Bethesda.Core/Plugins/Aspects/IKeyworded.cs
> +                if (cache.TryResolve(keywordForm, out keyword!))
Oh, then maybe this:
`if (cache.TryResolve<TKeyword>(keywordForm, out var keyword))`

2023-08-26 21:25 UTC, Noggog approved these changes

2023-08-26 22:02 UTC, MarkKoz commented on Mutagen.Bethesda.Core/Plugins/Aspects/IKeyworded.cs
> +                if (cache.TryResolve(keywordForm, out keyword!))
Ah yeah, that did it. So `TKeyword?` is fine, but it has to be used with `TryResolve<TKeyword>`. Otherwise, it uses ` TryResolve<TMajor>`, and that does not like `TKeyword?`.

2023-08-27 01:52 UTC, Noggog approved these changes

2023-08-27 01:52 UTC, merged