feat: add empty definitions for basically all missing major records
Mutagen-Modding/Mutagen pull request #481
Opened 2023-09-12 22:14 UTC by FlayaN

Hello! I did a python script to generate empty definitions for basically all major records (only added, discarded if a definition already exists)

You can decide if this is needed or not! No bad feelings, only some effort to fill in the script with the record and their names

Using this template: (named TEMPLATE.xml)
```xml
<?xml version="1.0" encoding="us-ascii"?>
<Loqui xmlns="http://tempuri.org/LoquiSource.xsd">
  <Object name="[NAME]" recordType="[RECORD_TYPE]" objType="Record" baseClass="StarfieldMajorRecord">
    <Fields>
    </Fields>
  </Object>
</Loqui>
```

I ran this python script

```py
records = {
    #"TES4": "Main File Header",      #// 01
    #"GRUP": "",      #// 02
    "GMST": "GameSetting",      #// 03
    "KYWD": "Keyword",      #// 04 BGSKeyword
    "FFKW": "Form Folder Keyword List",      #// 05 BGSFormFolderKeywordList
    "LCRT": "LocationReferenceType",      #// 06 BGSLocationRefType
    "AACT": "ActionRecord",      #// 07 BGSAction
    "TRNS": "Transform",      #// 08 BGSTransform
    "TXST": "TextureSet",      #// 09 BGSTextureSet
    "GLOB": "Global",      #// 0A TESGlobal
    "DMGT": "DamageType",      #// 0B BGSDamageType
    "CLAS": "Class",      #// 0C TESClass
    "FACT": "Faction",      #// 0D TESFaction
    "AFFE": "AffinityEvent",      #// 0E BGSAffinityEvent
    "HDPT": "HeadPart",      #// 0F BGSHeadPart
    "EYES": "Eyes",      #// 10 TESEyes
    "RACE": "Race",      #// 11 TESRace
    "SOUN": "SoundMarker",      #// 12 TESSound
    "SECH": "Sound Echo Marker",      #// 13 BGSSoundEcho
    "ASPC": "AcousticSpace",      #// 14 BGSAcousticSpace
    ###################"AOPF": "Audio Occlusion Primitive",      #// 15 BGSAudioOcclusionPrimitive
    "SKIL": "SkillRecord",      #// 16
    "MGEF": "MagicEffect",      #// 17 EffectSetting
    "SCPT": "Script",      #// 18 Script
    "LTEX": "LandscapeTexture",      #// 19 TESLandTexture
    "PDCL": "Projected Decal",      #// 1A BGSProjectedDecal
    "ENCH": "ObjectEffect",      #// 1B EnchantmentItem
    "SPEL": "Spell",      #// 1C SpellItem
    "SCRL": "Scroll",      #// 1D ScrollItem
    "ACTI": "Activator",      #// 1E TESObjectACTI
    "TACT": "TalkingActivator",      #// 1F BGSTalkingActivator
    "CURV": "Curve Table",      #// 20 BGSCurveForm
    "CUR3": "Curve 3D",      #// 21 BGSCurve3DForm
    "ARMO": "Armor",      #// 22 TESObjectARMO
    "BOOK": "Book",      #// 23 TESObjectBOOK
    "CONT": "Container",      #// 24 TESObjectCONT
    "DOOR": "Door",      #// 25 TESObjectDOOR
    "INGR": "Ingredient",      #// 26 IngredientItem
    "LIGH": "Light",      #// 27 TESObjectLIGH
    "MISC": "MiscItem",      #// 28 TESObjectMISC
    "STAT": "Static",      #// 29 TESObjectSTAT
    "SCOL": "StaticCollection",      #// 2A BGSStaticCollection
    "PKIN": "PackIn",      #// 2B BGSPackIn
    "MSTT": "MoveableStatic",      #// 2C BGSMovableStatic
    "GRAS": "Grass",      #// 2D TESGrass
    "FLOR": "Flora",      #// 2E TESFlora
    "FURN": "Furniture",      #// 2F TESFurniture
    "WEAP": "Weapon",      #// 30 TESObjectWEAP
    "AMMO": "Ammunition",      #// 31 TESAmmo
    "NPC_": "Npc",      #// 32 TESNPC
    "LVLN": "LeveledNpc",      #// 33 TESLevCharacter
    "LVLP": "Leveled Pack In",      #// 34 BGSLevPackIn
    "KEYM": "Key",      #// 35 TESKey
    "ALCH": "Ingestible",      #// 36 AlchemyItem
    "IDLM": "IdleMarker",      #// 37 BGSIdleMarker
    "BMMO": "Biome Marker",      #// 38 BGSBiomeMarkerObject
    "NOTE": "Note",      #// 39 BGSNote        # HOLOTAPE IN FO4 mutagen?
    "PROJ": "Projectile",      #// 3A BGSProjectile
    "HAZD": "Hazard",      #// 3B BGSHazard
    "BNDS": "BendableSpline",      #// 3C BGSBendableSpline
    "SLGM": "SoulGem",      #// 3D TESSoulGem
    "TERM": "Terminal",      #// 3E BGSTerminal
    "LVLI": "Leveled Item",      #// 3F TESLevItem
    "GBFT": "Generic Base Form Template",      #// 40 BGSGenericBaseFormTemplate
    "GBFM": "Generic Base Form",      #// 41 BGSGenericBaseForm
    "LVLB": "Leveled Base Form",      #// 42 BGSLevGenericBaseForm
    "WTHR": "Weather",      #// 43 TESWeather
    "WTHS": "Weather Settings",      #// 44 BGSWeatherSettingsForm
    "CLMT": "Climate",      #// 45 TESClimate
    "SPGD": "Shader Particle Geometry",      #// 46 BGSShaderParticleGeometryData
    "REGN": "Region",      #// 47 TESRegion
    "NAVI": "Navigation Mesh Info Map",      #// 48 NavMeshInfoMap
    "CELL": "Cell",      #// 49 TESObjectCELL
    "REFR": "PlacedObject",      #// 4A TESObjectREFR
    "ACHR": "PlacedNpc",      #// 4B Actor
    #"PMIS": "PlacedMissile",      #// 4C MissileProjectile   # these are combined into PlacedTrap
    #"PARW": "PlacedArrow",      #// 4D ArrowProjectile       # these are combined into PlacedTrap
    #"PGRE": "PlacedTrap",      #// 4E GrenadeProjectile      # these are combined into PlacedTrap
    #"PBEA": "PlacedBeam",      #// 4F BeamProjectile         # these are combined into PlacedTrap
    #"PFLA": "PlacedFlame",      #// 50 FlameProjectile       # these are combined into PlacedTrap
    #"PCON": "PlacedCone",      #// 51 ConeProjectile         # these are combined into PlacedTrap
    #"PPLA": "PlacedPlasma",      #// 52 PlasmaProjectile                 # these are combined into PlacedTrap
    #"PBAR": "PlacedBarrier",      #// 53 BarrierProjectile   # these are combined into PlacedTrap
    #"PEMI": "PlacedEmitter",      #// 54 EmitterProjectile                # these are combined into PlacedTrap
    #"PHZD": "PlacedHazard",      #// 55 Hazard              # these are combined into PlacedTrap
    "WRLD": "Worldspace",      #// 56 TESWorldSpace
    "NAVM": "NavigationMesh",      #// 57 NavMesh
    "TLOD": "TLODRecord",      #// 58
    "DIAL": "DialogTopic",      #// 59 TESTopic
    "INFO": "DialogResponses",      #// 5A TESTopicInfo
    "QUST": "Quest",      #// 5B TESQuest
    "IDLE": "IdleAnimation",      #// 5C TESIdleForm
    "PACK": "Package",      #// 5D TESPackage
    "CSTY": "CombatStyle",      #// 5E TESCombatStyle
    "LSCR": "LoadScreen",      #// 5F TESLoadScreen
    "LVSP": "LeveledSpell",      #// 60 TESLevSpell
    "ANIO": "Animated Object",      #// 61 TESObjectANIO
    "WATR": "Water",      #// 62 TESWaterForm
    "EFSH": "EffectShader",      #// 63 TESEffectShader
    "TOFT": "TOFTRecord",      #// 64
    "EXPL": "Explosion",      #// 65 BGSExplosion
    "DEBR": "Debris",      #// 66 BGSDebris
    "IMGS": "ImageSpace",      #// 67 TESImageSpace
    "IMAD": "ImageSpaceAdapter",      #// 68 TESImageSpaceModifier
    "FLST": "FormList",      #// 69 BGSListForm
    "PERK": "Perk",      #// 6A BGSPerk
    "BPTD": "BodyPartData",      #// 6B BGSBodyPartData
    "ADDN": "AddonNode",      #// 6C BGSAddonNode
    "AVIF": "ActorValueInformation",      #// 6D ActorValueInfo
    "CAMS": "CameraShot",      #// 6E BGSCameraShot
    "CPTH": "CameraPath",      #// 6F BGSCameraPath
    "VTYP": "VoiceType",      #// 70 BGSVoiceType
    "MATT": "MaterialType",      #// 71 BGSMaterialType
    "IPCT": "Impact",      #// 72 BGSImpactData
    "IPDS": "ImpactDataSet",      #// 73 BGSImpactDataSet
    "ARMA": "ArmorAddon",      #// 74 TESObjectARMA
    "LCTN": "Location",      #// 75 BGSLocation
    "MESG": "Message",      #// 76 BGSMessage
    "RGDL": "RGDLRecord",      #// 77
    "DOBJ": "DefaultObjectManager",      #// 78 BGSDefaultObjectManager
    "DFOB": "DefaultObject",      #// 79 BGSDefaultObject
    "LGTM": "LightingTemplate",      #// 7A BGSLightingTemplate
    "MUSC": "MusicType",      #// 7B BGSMusicType
    "FSTP": "Footstep",      #// 7C BGSFootstep
    "FSTS": "Footstep Set",      #// 7D BGSFootstepSet
    #"SMBN": "StoryManagerBranchNode",      #// 7E BGSStoryManagerBranchNode        #Combined into StoryManagerNodes
    #"SMQN": "StoryManagerQuestNode",      #// 7F BGSStoryManagerQuestNode          #Combined into StoryManagerNodes
    #"SMEN": "StoryManagerEventNode",      #// 80 BGSStoryManagerEventNode          #Combined into StoryManagerNodes
    "DLBR": "DialogBranch",      #// 81 B [...]

2023-09-13 00:34 UTC, Noggog requested changes
Hey!  Thanks for the thought/work!

Made one comment about a typo, but that's a mostly non-issue.

My main concern overall is that we may be copy pasting in tons of content without a mechanism for recognizing/removing stuff that isn't needed.  For example, `Soul Gem` `SLGM` is on this list (cuz i presume it's still on the xedit list?), but it doesn't show up in Starfield.esm at all.  

By mass adding all this now, we might end up with just some vestigial whatevers that we dont notice shouldnt be here at all.  This is sort of why I've so far opted to not just copy paste Fo4 definitions and work from there.  That can lead to lots of fields that are defined, but no one realizes are vestigial.   Feels better to me to "add-as-seen" as much as possible?  The copy pasting can still occur, but just a bit more on-demand when it's actually seen and thus known to be needed?

xEdit seems to be working the other direction.  Maybe they'll do a cleaning pass at the end to compensate, but I'd worry about us inheriting a lot of junk that way if we're not careful and also doing cleaning passes.   If you want to write a script to cross reference this with the content in Starfield, we can weed out any vestigial bits that way.   Here's an example of some of the low level tooling that's able to iterate over the raw record data structures more directly to do jobs like this:

https://github.com/Mutagen-Modding/Mutagen.Bethesda.Generation.Tools/blob/main/Mutagen.Bethesda.Generation.Tools/ContentAnalyzers/DumpSubrecords.cs

2023-09-13 00:34 UTC, Noggog commented on Mutagen.Bethesda.Starfield/Records/Major Records/WWiseKeywordMappin.xml
> +  <Object name="WWiseKeywordMappin" recordType="WKMF" objType="Record" baseClass="StarfieldMajorRecord" GUID="65181f65-a970-4534-afaf-7d8bd6706173" ID="896">
Supposed to be Mapping?  haha

2023-09-13 00:34 UTC, Noggog commented on Mutagen.Bethesda.Starfield/Records/Major Records/SoulGem.xml
> +  <Object name="SoulGem" recordType="SLGM" objType="Record" baseClass="StarfieldMajorRecord" GUID="6674fb92-ae7f-4836-9c07-583e8ae378dc" ID="871">
Doesn't actually show in Starfield.esm

2023-09-16 10:58 UTC, FlayaN commented on Mutagen.Bethesda.Starfield/Records/Major Records/WWiseKeywordMappin.xml
> +  <Object name="WWiseKeywordMappin" recordType="WKMF" objType="Record" baseClass="StarfieldMajorRecord" GUID="65181f65-a970-4534-afaf-7d8bd6706173" ID="896">
haha nice call, fixed!

2023-09-16 10:59 UTC, FlayaN commented on Mutagen.Bethesda.Starfield/Records/Major Records/SoulGem.xml
> +  <Object name="SoulGem" recordType="SLGM" objType="Record" baseClass="StarfieldMajorRecord" GUID="6674fb92-ae7f-4836-9c07-583e8ae378dc" ID="871">
Added starfield.esm filter so it's only generating if it's present in starfield.esm

2023-09-16 11:03 UTC, FlayaN commented
>https://github.com/Mutagen-Modding/Mutagen.Bethesda.Generation.Tools/blob/main/Mutagen.Bethesda.Generation.Tools/ContentAnalyzers/DumpSubrecords.cs

Thanks for the link! I basically did a local change of that to remove the -m filter and print all major records found in the output so I could paste that into the python script i posted here!

2023-09-16 20:40 UTC, Noggog approved these changes
Awesome, thanks for the adjustment!

2023-09-16 20:41 UTC, merged