Add Starfield weather definition (based on Fallout 4, not a lot changed)
Mutagen-Modding/Mutagen pull request #486
Opened 2023-09-25 11:47 UTC by Elscrux

2023-09-25 19:24 UTC, Noggog requested changes

2023-09-25 19:24 UTC, Noggog commented on Mutagen.Bethesda.Starfield/Records/Major Records/Weather.xml
> +          <Break />
Let's see if we can remove the Breaks since we're on a new game

2023-09-25 19:24 UTC, Noggog commented on Mutagen.Bethesda.Starfield/Records/Major Records/WeatherAmbientColorSet.cs
> +    // IAmbientColorsGetter IWeatherAmbientColorSetGetter.this[TimeOfDay time] => time switch
Can these be uncommented out?

2023-09-26 09:04 UTC, Elscrux commented on Mutagen.Bethesda.Starfield/Records/Major Records/WeatherAmbientColorSet.cs
> +    // IAmbientColorsGetter IWeatherAmbientColorSetGetter.this[TimeOfDay time] => time switch
This is done because Starfield doesn't have this `TimeOfDay` enum. Instead, there is some kind of `TimeOfDayData` that hasn't been decoded yet, so there is not much to be done I think.

2023-09-26 09:04 UTC, Elscrux commented on Mutagen.Bethesda.Starfield/Records/Major Records/Weather.xml
> +          <Break />
Ok, I'll try. What do those Breaks to btw?

2023-09-26 09:07 UTC, Noggog commented on Mutagen.Bethesda.Starfield/Records/Major Records/Weather.xml
> +          <Break />
Some fields are added as the FormVersion increases.  Rather than figuring out the exact formversion that it's added (sometimes impossible to know), the Break is a way to just say "I know content past here might be missing occasionally, so be aware"

With a newer game though, I imagine all the fields from the past game should always be present, so the breaks from old definitions probably arent needed

2023-09-26 12:08 UTC, Elscrux commented on Mutagen.Bethesda.Starfield/Records/Major Records/Weather.xml
> +          <Break />
I had to fix some bugs that I somehow didn't see before, but now it also works without breaks :)

2023-09-26 22:27 UTC, closed without merging