Add MajorRecordTypeEnumerator
Mutagen-Modding/Mutagen pull request #513
Opened 2024-04-02 15:29 UTC by Elscrux

Implements #510 

@Noggog Let me know if this is what you were thinking or if I should change anything.

Btw, could you expand the .editorconfig with the guidelines you use for Mutagen. I keep putting the curly braces in the wrong place lol.

2024-04-02 21:55 UTC, Noggog requested changes

2024-04-02 21:55 UTC, Noggog commented on Mutagen.Bethesda.Core/Plugins/Records/Mapping/MajorRecordTypeEnumerator.cs
> +	private static readonly Dictionary<GameCategory, List<ILoquiRegistration>> Registrations = new();
Right now this is vulnerable to multithreading collisions, as many threads can call the accessor functions and all be filling this dictionary/list in parallel

I'd modify this to a `Lazy<IReadOnlyDictionary<....>>` with the GetRegistrations logic as the callback to fulfill the lazy variable

The public accessors can then just access the lazy variable and do the lookup.  The lazy variables have thread safety mechanics internally

2024-04-02 21:55 UTC, Noggog commented on Mutagen.Bethesda.Core/Plugins/Records/Mapping/MajorRecordTypeEnumerator.cs
> +				string.Equals(x.ClassType.Namespace, gameNamespace, StringComparison.Ordinal)
Might break if we change namespaces (not that we would).  Maybe downgrade it to Contains(..) on the game category string?

Let's make sure to turn the game category into a string outside the loop (like this PR is currently doing), or use `Enums<GameCategory>.ToStringFast(...)`, as ToStringing enums is actually heavyier than expected

Might be a better way besides string checking namespaces, but not coming to my brain offhand

2024-04-02 21:55 UTC, Noggog commented on Mutagen.Bethesda.Core/Plugins/Records/Mapping/MajorRecordTypeEnumerator.cs
> +	}
I think we can unify this into one call, and expose a record like `InterfaceMappingTypes`, but maybe call it `RecordTypes` and have Class/Getter/Setter as required fields?

Then we can just have one function that returns this record, and the user can get whatever subtype they desire from there

2024-04-02 22:05 UTC, Elscrux commented on Mutagen.Bethesda.Core/Plugins/Records/Mapping/MajorRecordTypeEnumerator.cs
> +	private static readonly Dictionary<GameCategory, List<ILoquiRegistration>> Registrations = new();
Wouldn't a ConcurrentDictionary also work?

2024-04-02 22:06 UTC, Elscrux commented on Mutagen.Bethesda.Core/Plugins/Records/Mapping/MajorRecordTypeEnumerator.cs
> +	private static readonly Dictionary<GameCategory, List<ILoquiRegistration>> Registrations = new();
The lazy variant would have to fill the whole directory for all categories when it's first called right? Otherwise it would have the same problem as the dictionary has now.

2024-04-04 04:04 UTC, Noggog commented on Mutagen.Bethesda.Core/Plugins/Records/Mapping/MajorRecordTypeEnumerator.cs
> +	private static readonly Dictionary<GameCategory, List<ILoquiRegistration>> Registrations = new();
Yes, if you used a lazy variable straight up it would have to do all the game categories up front to make sense.
you could do a concurrent dictionary as well if you wanted to go that route

2024-04-04 11:32 UTC, Elscrux commented on Mutagen.Bethesda.Core/Plugins/Records/Mapping/MajorRecordTypeEnumerator.cs
> +	private static readonly Dictionary<GameCategory, List<ILoquiRegistration>> Registrations = new();
I used the ConcurrentDictionary as it seemed easiest and most efficient :)

2024-04-06 04:58 UTC, Noggog approved these changes

2024-04-06 04:58 UTC, merged