Add WithAllParentMasters binary write builder option
Mutagen-Modding/Mutagen pull request #547
Opened 2024-08-29 22:32 UTC by Elscrux

2024-08-29 23:14 UTC, Noggog requested changes

2024-08-29 23:14 UTC, Noggog commented on Mutagen.Bethesda.Core/Plugins/Binary/Translations/BinaryWriteBuilder.cs
> +            }
Can we refactor this logic to an internal component that takes in the `LO` and returns the `IEnumerable<ModKey>`?

Main thing is that this builder call shouldn't be the one specifying the LO.  The LO is set via other builder calls, and this logic should be run "lazily" at the end once all the bits are set and the Write is actually called

--- 

To get the "laziness", a system like the `_loadOrderSetter` will need to be added like a `_mastersContentSetter`.   When called during the "pull together" phase, it would pull in the LO set right before, and then use that to calculate the masters.   I can do this part if you want, as it's pretty fiddly and error prone

2024-08-30 10:19 UTC, Elscrux commented on Mutagen.Bethesda.Core/Plugins/Binary/Translations/BinaryWriteBuilder.cs
> +            }
I looked at the `_loadOrderSetter` before, but the load order it has just has a limited `IModFlags` interface or so, which didn't allow master references to be looked at. I didn't want to edit the existing builder code so I went this way for now.

2024-09-02 19:07 UTC, Noggog commented on Mutagen.Bethesda.Core/Plugins/Binary/Translations/BinaryWriteBuilder.cs
> +            }
True true.  hmm

Well.   I think the idea is that load order is mainly used for ordering.  Whereas the Data folder is used for looking up info about mods.  So the presence of `ILoadOrderGetter<IModFlagsGetter> loadOrder` is maybe bad... and should only be `ILoadOrderGetter<ModKey> loadOrder`

If that was the case, then someone like yourself using `WithAllParentMasters()` would:
- not supply anything in the `WithAllParentMasters()` call itself
- Would include `WithDataFolder(...)` to let the system know where to read mods from to find all the parent masters
- Would include `WithLoadOrder(...)` to let the system know how to order all the parent masters

Maybe as a followup, we could remove the `ILoadOrderGetter<IModFlagsGetter> loadOrder`, but I would want to deep dive on it to make sure that's a good cut.

2024-09-07 04:55 UTC, merged