Top Level Groups Enumeration
Mutagen-Modding/Mutagen pull request #563
Opened 2024-10-17 16:25 UTC by some1one

+added WhereNotNull IEnumerable Extension
+added GetTopLevelMajorRecordTypes to MajorRecordTypeEnumerator
+added to cheatsheat
*changed cache list type to immutableArray

2024-10-17 16:33 UTC, some1one commented
rebased on dev and removed the doc commits from the other pull request

2024-10-19 07:24 UTC, Noggog requested changes
Rebase went a bit weird and some commits got in both, but all good!
![image](https://github.com/user-attachments/assets/a9cc3d6e-e1e8-45cb-bad7-b436ad3273f1)

Only thing I'd say is maybe (re)move the null extension, and should be good to go!

2024-10-19 07:24 UTC, Noggog commented on Mutagen.Bethesda.Core/Extensions/EnumerableExt.cs
> +    public static IEnumerable<T> WhereNotNull<T>(this IEnumerable<T?> enumer)
Already got an extension like this over in https://github.com/Noggog/CSharpExt/blob/89a5e0918ae8a212b592b890a5b62ca1209f2120/Noggog.CSharpExt/Extensions/EnumerableExt.cs#L257

But I do like the `Where__` naming better.   Feel free to open a PR over there, and mark the old ones obsolete

2024-10-19 08:24 UTC, Noggog commented
Ah, i can handle the small tweaks.   Like i mentioned, gonna remove the new WhereNotNull method, but feel free to add to CSharpExt if you feel inspired to do so

2024-10-19 08:25 UTC, Noggog approved these changes

2024-10-19 08:25 UTC, merged