Condition Parameter Generation
Mutagen-Modding/Mutagen pull request #567
Opened 2024-11-16 12:08 UTC by Elscrux

Generate Parameter1 and Parameter2 properties to enable access to parameters without knowing the concrete condition data type

2024-11-18 01:26 UTC, Noggog requested changes
On a good track.  Few more things to add, i think!

2024-11-18 01:26 UTC, Noggog commented on Mutagen.Bethesda.Skyrim/Records/Common Subrecords/CanFlyHereConditionData_Generated.cs
> +            get => null;
Getting null here feels fine.  Feels a bit odd to just do nothing in the set.   Gut is telling me we should throw if the given value is not null (similar to how we throw if the type is wrong for used parameters)

2024-11-18 01:26 UTC, Noggog commented on Mutagen.Bethesda.Skyrim/Records/Common Subrecords/GetCrimeGoldViolentConditionData_Generated.cs
> +            set => Faction = (value is IFormLinkOrIndex<IFactionGetter> v ? v : throw new ArgumentException());
I like the throw if the type is wrong.

Might be nice to add `Type Parameter1Type { get; }` parameter so that the user can know/expect what type should be given?

2024-11-18 01:26 UTC, Noggog commented on Mutagen.Bethesda.Generation/Modules/Plugin/ConditionDataModule.cs
> +                        sb.AppendLine();
Putting it here too, but we shuld check if it's not null and throw argument exception if it's not null?

2024-11-18 01:26 UTC, Noggog commented on Mutagen.Bethesda.Generation/Modules/Plugin/ConditionDataModule.cs
> +            sb.AppendLine($"public object? Parameter{i}");
Let's add `public Type? Parameter1Type` here as well

2024-11-18 01:26 UTC, Noggog commented on Mutagen.Bethesda.Skyrim/Records/Common Subrecords/ConditionData.cs
> +    public object? Parameter1
Defining these like this makes it harder for the implementing classes to implement the actual setups.

In theory, these could be `virtual`, which would mean the inheriting classes would need to `override`.
that's one way.

The way I've typically been doing it is writing them like the lines above, which specifically associate them with the interface call, rather than being straight fields on the class

I think this allows the inheriting classes to define the fields for real themselves for their implementation of the interface.

2024-11-18 16:34 UTC, Elscrux commented on Mutagen.Bethesda.Skyrim/Records/Common Subrecords/CanFlyHereConditionData_Generated.cs
> +            get => null;
I was worrying this could lead to strange behavior when you are working on generic conditions. Setting a property might not be intuitively something where you expect it throws when doing it? What do you think? You can of course just add a try catch block when you get any issues with this.

2024-11-18 16:35 UTC, Elscrux commented on Mutagen.Bethesda.Skyrim/Records/Common Subrecords/GetCrimeGoldViolentConditionData_Generated.cs
> +            set => Faction = (value is IFormLinkOrIndex<IFactionGetter> v ? v : throw new ArgumentException());
Yeah that's a good idea

2024-11-18 17:03 UTC, Elscrux commented on Mutagen.Bethesda.Generation/Modules/Plugin/ConditionDataModule.cs
> +                        sb.AppendLine();
I think this is a similar design decision as throwing the other exception. Should be both or none.

2024-11-18 17:32 UTC, Elscrux commented on Mutagen.Bethesda.Skyrim/Records/Common Subrecords/ConditionData.cs
> +    public object? Parameter1
I implemented the interfaces explicitly. I think it might be good if we didn't implement the properties explicitly in ConditionData so we enforce that concrete types implement it (we could make them abstract for example).

2024-11-18 17:59 UTC, Noggog commented on Mutagen.Bethesda.Skyrim/Records/Common Subrecords/CanFlyHereConditionData_Generated.cs
> +            get => null;
Yeah, not a great way either route... but I think that's just the price of writing generic API that is trying to handle everything.

The downside of the current setup is that users will expect that if they set the field and it "went through", that something was modified.  But instead, it didnt modify anything, and was just a "silent error" of sorts.

The throw at least is something the user can detect/handle, vs the silent error just leads to more of an undetectable paranoia, imo

2024-11-18 18:01 UTC, Noggog commented on Mutagen.Bethesda.Skyrim/Records/Common Subrecords/ConditionData.cs
> +    public object? Parameter1
>  think it might be good if we didn't implement the properties explicitly in ConditionData 

agreed!

2024-11-19 18:12 UTC, Noggog approved these changes

2024-11-19 18:12 UTC, Noggog commented on Mutagen.Bethesda.Skyrim/Records/Common Subrecords/ConditionData.cs
> +            conditionData.Parameter1 = value;
I think ideally it wouldn't need to throw and catch to detect a false (exceptions are a decent overhead).  In theory we could do the same check we do in the parameter set, and just return false
`if (value is not IFormLinkOrIndex<IKeywordGetter>) return false;`
Would be a hyperoptimization.. pretty low prio

2024-11-19 18:21 UTC, Elscrux commented on Mutagen.Bethesda.Skyrim/Records/Common Subrecords/ConditionData.cs
> +            conditionData.Parameter1 = value;
That would need to be implemented for every concrete condition data though right?

2024-11-19 19:19 UTC, Noggog commented on Mutagen.Bethesda.Skyrim/Records/Common Subrecords/ConditionData.cs
> +            conditionData.Parameter1 = value;
ah true.  Probably fine for now

2024-11-19 19:20 UTC, merged